#!/bin/bash
clear
read  -p "Estas segur de continuar avançant?: " v1
v2=0
while [ $v2 == 0 ]
do
	case $v1 in
		'exit')
			v2=1
			sudo xdg-open https://www.youtube.com/watch?v=jaLDoWqIq2M 
		;;
		*)
			read  -p "Estas segur de continuar avançant?: " v1 ;;
esac
done
